server:
  port: 8010
spring:
  application:
    name: microservice-consumer-movie-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:9000/eureka/
  instance:
    preferIpAddress: true
    hostname: user