server:
  port: 10001
spring:
  application:
    name: micro-service-monitor-log 
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    
    database-platform: org.hibernate.dialect.MySQLDialect
#      dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_example2?useUnicode=true&characterEncoding=utf8 
    username: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:9000/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true
    hostname: localhost